const tileTypeLabels = {
  "-1": "Empty",
  0: "Platform",
  8: "Object: Spike: Left",
  9: "Object: Spike: Top",
  10: "Object: Clamp: Right",
  11: "Object: Clamp: Bottom",
  12: "Object: Pipe: Right",
  13: "Background",
  14: "Object: Pipe: Left",
  15: "Object: Water: Head",
  16: "Object: Gold Box: Locked",
  17: "Object: Gold Box: Empty",
  18: "Object: Key",
  19: "Platform",
  20: "Solid",
  21: "Platform",
  22: "Solid",
  23: "Platform",
  27: "Object: Spike: Bottom",
  28: "Object: Spike: Right",
  29: "Object: Clamp: Top",
  30: "Object: Clamp: Left",
  31: "Object: Pipe: Bottom",
  32: "Object: Waterfall: Head",
  33: "Object: Diamond",
  34: "Object: Water: Body",
  35: "Object: Gold Box: Special",
  36: "Object: Gold Box: Coin",
  37: "Object: Coin",
  38: "Platform",
  42: "Background",
  46: "Object: Spring: Bottom",
  47: "Object: Spring: Right",
  48: "Object: Lever",
  49: "Object: Button: Right",
  50: "Background",
  51: "Object: Waterfall: Body",
  52: "Background",
  54: "Object: Box: Random",
  55: "Object: Box: Empty",
  56: "Platform",
  58: "Solid",
  59: "Platform",
  60: "Solid",
  61: "Background",
  65: "Object: Spring: Left",
  66: "Object: Heart",
  67: "Object: Button: Bottom",
  68: "Object: Button: Left",
  69: "Object: Pipe: Top",
  70: "Object: Waterfall: Foot",
  71: "Background",
  73: "Object: Box: Special",
  74: "Object: Box: Coin",
  75: "Object: Ladder",
  76: "Platform",
  80: "Background",
  81: "Platform",
  83: "Background",
  84: "Platform",
  92: "Background",
  94: "Object: Ladder",
  95: "Platform",
  96: "Solid",
  97: "Platform",
  98: "Solid",
  99: "Background",
  106: "Object: Flag",
  107: "Background",
  109: "Solid",
  110: "Object: Rope: Head: Top",
  111: "Background",
  113: "Object: Sign",
  114: "Background",
  126: "Solid",
  129: "Object: Rope: Body: Vertical",
  130: "Background",
  145: "Object: Rope: Head: Left",
  146: "Object: Rope: Body: Horizontal",
  147: "Object: Rope: Head: Right",
  148: "Object: Rope: Head: Bottom",
  149: "Background",
};

function getPreviousTileType(tileIndex) {
  for (let i = tileIndex - 1; i >= -1; i--) {
    if (tileTypeLabels[i] !== undefined) {
      return tileTypeLabels[i];
    }
  }
}

export function getTileTypeLabel(tileIndex) {
  const type = tileTypeLabels[tileIndex] ?? getPreviousTileType(tileIndex);
  return `${type}`;
}
