const tileTypeLabels = {
  "-1": "Empty",
  0: "Platform",
  4: "Background",
  10: "Platform",
  14: "Object: Spring: Bottom",
  15: "Object: Spring: Right",
  16: "Object: Lever",
  17: "Object: Spike: Left",
  18: "Object: Clamp: Right",
  19: "Object: Clamp: Bottom",
  20: "Object: Ladder",
  21: "Object: Key",
  22: "Object: Coin",
  23: "Solid",
  25: "Platform",
  26: "Solid",
  27: "Background",
  36: "Object: Flag",
  37: "Object: Spring: Left",
  38: "Object: Heart",
  39: "Object: Spike: Right",
  40: "Object: Spike: Top",
  41: "Object: Clamp: Top",
  42: "Object: Clamp: Left",
  43: "Object: Ladder",
  44: "Object: Gold Box: Locked",
  45: "Object: Gold Box: Empty",
  46: "Platform",
  50: "Background",
  60: "Object: Button: Bottom",
  61: "Object: Button: Right",
  62: "Object: Button: Left",
  63: "Object: Spike: Bottom",
  64: "Object: Rope: Head: Left",
  65: "Object: Rope: Body: Horizontal",
  66: "Object: Rope: Head: Right",
  67: "Object: Gold Box: Special",
  68: "Object: Gold Box: Coin",
  69: "Solid",
  71: "Platform",
  72: "Solid",
  73: "Background",
  83: "Object: Pipe: Right",
  84: "Background",
  85: "Object: Pipe: Left",
  86: "Object: Water: Head",
  87: "Background",
  89: "Object: Rope: Head: Top",
  90: "Object: Box: Random",
  91: "Object: Box: Empty",
  92: "Platform",
  96: "Background",
  103: "Platform",
  105: "Background",
  106: "Object: Pipe: Bottom",
  107: "Object: Waterfall: Head",
  108: "Object: Diamond",
  109: "Object: Water: Body",
  110: "Background",
  112: "Object: Rope: Body: Vertical",
  113: "Object: Box: Special",
  114: "Object: Box: Coin",
  115: "Solid",
  117: "Platform",
  118: "Solid",
  119: "Platform",
  124: "Background",
  128: "Platform",
  129: "Background",
  130: "Object: Waterfall: Body",
  131: "Background",
  135: "Object: Rope: Head: Bottom",
  136: "Platform",
  138: "Background",
  146: "Platform",
  147: "Background",
  152: "Object: Pipe: Top",
  153: "Object: Waterfall: Foot",
  154: "Background",
  158: "Solid",
  161: "Background",
  169: "Platform",
  171: "Background",
  174: "Platform",
  178: "Background",
  182: "Object: Sign",
  183: "Solid",
};

function getPreviousTileType(tileIndex) {
  for (let i = tileIndex - 1; i >= -1; i--) {
    if (tileTypeLabels[i] !== undefined) {
      return tileTypeLabels[i];
    }
  }
}

export function getTileTypeLabel(tileIndex) {
  const type = tileTypeLabels[tileIndex] ?? getPreviousTileType(tileIndex);
  return `Type: ${type}`;
}
